use_frameworks!

target 'SubstrateSdkExample' do
  pod 'SubstrateSdk', :path => '../'
  pod 'Starscream', :git => 'https://github.com/ERussel/Starscream.git', :branch => 'feature/without-origin'
  pod 'SwiftLint'

  target 'SubstrateSdkTests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
