platform :ios, '14.0'
use_frameworks!

target 'SubstrateSdkExample' do
  pod 'SubstrateSdk', :path => '../'
  pod 'Operation-iOS', :git => 'https://github.com/novasamatech/Operation-iOS.git', :tag => '2.1.0'
  pod 'Starscream', :git => 'https://github.com/ERussel/Starscream.git', :branch => 'feature/without-origin'
  pod 'SwiftLint'
  pod 'NovaCrypto', :git => 'https://github.com/novasamatech/Crypto-iOS.git', :commit => 'c60957339004bc9ceb9dcf4e205e10428549e782'
  pod 'secp256k1.c', :git => 'https://github.com/novasamatech/secp256k1.c', :tag => '0.1.3'
  pod 'sr25519.c', :git => 'https://github.com/novasamatech/sr25519.c', :tag => '0.1.0'
  pod 'ed25519.c', :git => 'https://github.com/novasamatech/ed25519.c', :tag => '0.1.1'
  pod 'blake2.c', :git => 'https://github.com/novasamatech/blake2.c', :tag => '0.1.0'

  target 'SubstrateSdkTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
  
  installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
    target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
      resource_bundle_target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end

end
